using isp.platformb2b.data.DatabaseModels;
using System.Collections.Generic;

namespace isp.platformb2b.data.Seeders
{
    public class seedTipoMoneda
    {
        public readonly static List<tipo_moneda> ListaMonedas = new List<tipo_moneda>
        {
            new tipo_moneda (){id_tipo_moneda="AED",divisa="Dírham de los Emiratos Árabes Unidos"},
            new tipo_moneda (){id_tipo_moneda="AFN",divisa="Afgani"},
            new tipo_moneda (){id_tipo_moneda="ALL",divisa="Lek"},
            new tipo_moneda (){id_tipo_moneda="AMD",divisa="Dram armenio"},
            new tipo_moneda (){id_tipo_moneda="ANG",divisa="Florín antillano neerlandés"},
            new tipo_moneda (){id_tipo_moneda="AOA",divisa="Kwanza"},
            new tipo_moneda (){id_tipo_moneda="ARS",divisa="Peso argentino"},
            new tipo_moneda (){id_tipo_moneda="AUD",divisa="Dólar australiano"},
            new tipo_moneda (){id_tipo_moneda="AWG",divisa="Florín arubeño"},
            new tipo_moneda (){id_tipo_moneda="AZN",divisa="Manat azerbaiyano"},
            new tipo_moneda (){id_tipo_moneda="BAM",divisa="Marco convertible"},
            new tipo_moneda (){id_tipo_moneda="BBD",divisa="Dólar de Barbados"},
            new tipo_moneda (){id_tipo_moneda="BDT",divisa="Taka"},
            new tipo_moneda (){id_tipo_moneda="BGN",divisa="Lev búlgaro"},
            new tipo_moneda (){id_tipo_moneda="BHD",divisa="Dinar bareiní"},
            new tipo_moneda (){id_tipo_moneda="BIF",divisa="Franco de Burundi"},
            new tipo_moneda (){id_tipo_moneda="BMD",divisa="Dólar bermudeño"},
            new tipo_moneda (){id_tipo_moneda="BND",divisa="Dólar de Brunéi"},
            new tipo_moneda (){id_tipo_moneda="BOB",divisa="Boliviano"},
            new tipo_moneda (){id_tipo_moneda="BOV",divisa="MVDOL"},
            new tipo_moneda (){id_tipo_moneda="BRL",divisa="Real brasileño"},
            new tipo_moneda (){id_tipo_moneda="BSD",divisa="Dólar bahameño"},
            new tipo_moneda (){id_tipo_moneda="BTN",divisa="Ngultrum"},
            new tipo_moneda (){id_tipo_moneda="BWP",divisa="Pula"},
            new tipo_moneda (){id_tipo_moneda="BYN",divisa="Rublo bielorruso"},
            new tipo_moneda (){id_tipo_moneda="BZD",divisa="Dólar beliceño"},
            new tipo_moneda (){id_tipo_moneda="CAD",divisa="Dólar canadiense"},
            new tipo_moneda (){id_tipo_moneda="CDF",divisa="Franco congoleño"},
            new tipo_moneda (){id_tipo_moneda="CHE",divisa="Euro WIR"},
            new tipo_moneda (){id_tipo_moneda="CHF",divisa="Franco suizo"},
            new tipo_moneda (){id_tipo_moneda="CHW",divisa="Franco WIR"},
            new tipo_moneda (){id_tipo_moneda="CLF",divisa="Unidad de fomento"},
            new tipo_moneda (){id_tipo_moneda="CLP",divisa="Peso chileno"},
            new tipo_moneda (){id_tipo_moneda="CNY",divisa="Yuan chino"},
            new tipo_moneda (){id_tipo_moneda="COP",divisa="Peso colombiano"},
            new tipo_moneda (){id_tipo_moneda="COU",divisa="Unidad de valor real"},
            new tipo_moneda (){id_tipo_moneda="CRC",divisa="Colón costarricense"},
            new tipo_moneda (){id_tipo_moneda="CUC",divisa="Peso convertible"},
            new tipo_moneda (){id_tipo_moneda="CUP",divisa="Peso cubano"},
            new tipo_moneda (){id_tipo_moneda="CVE",divisa="Escudo caboverdiano"},
            new tipo_moneda (){id_tipo_moneda="CZK",divisa="Corona checa"},
            new tipo_moneda (){id_tipo_moneda="DJF",divisa="Franco yibutiano"},
            new tipo_moneda (){id_tipo_moneda="DKK",divisa="Corona danesa"},
            new tipo_moneda (){id_tipo_moneda="DOP",divisa="Peso dominicano"},
            new tipo_moneda (){id_tipo_moneda="DZD",divisa="Dinar argelino"},
            new tipo_moneda (){id_tipo_moneda="EGP",divisa="Libra egipcia"},
            new tipo_moneda (){id_tipo_moneda="ERN",divisa="Nakfa"},
            new tipo_moneda (){id_tipo_moneda="ETB",divisa="Birr etíope"},
            new tipo_moneda (){id_tipo_moneda="EUR",divisa="Euro",usual=true},
            new tipo_moneda (){id_tipo_moneda="FJD",divisa="Dólar fiyiano"},
            new tipo_moneda (){id_tipo_moneda="FKP",divisa="Libra malvinense"},
            new tipo_moneda (){id_tipo_moneda="GBP",divisa="Libra esterlina"},
            new tipo_moneda (){id_tipo_moneda="GEL",divisa="Lari"},
            new tipo_moneda (){id_tipo_moneda="GHS",divisa="Cedi ghanés"},
            new tipo_moneda (){id_tipo_moneda="GIP",divisa="Libra de Gibraltar"},
            new tipo_moneda (){id_tipo_moneda="GMD",divisa="Dalasi"},
            new tipo_moneda (){id_tipo_moneda="GNF",divisa="Franco guineano"},
            new tipo_moneda (){id_tipo_moneda="GTQ",divisa="Quetzal"},
            new tipo_moneda (){id_tipo_moneda="GYD",divisa="Dólar guyanés"},
            new tipo_moneda (){id_tipo_moneda="HKD",divisa="Dólar de Hong Kong"},
            new tipo_moneda (){id_tipo_moneda="HNL",divisa="Lempira"},
            new tipo_moneda (){id_tipo_moneda="HRK",divisa="Kuna"},
            new tipo_moneda (){id_tipo_moneda="HTG",divisa="Gourde"},
            new tipo_moneda (){id_tipo_moneda="HUF",divisa="Forinto"},
            new tipo_moneda (){id_tipo_moneda="IDR",divisa="Rupia indonesia"},
            new tipo_moneda (){id_tipo_moneda="ILS",divisa="Nuevo shéquel israelí"},
            new tipo_moneda (){id_tipo_moneda="INR",divisa="Rupia india"},
            new tipo_moneda (){id_tipo_moneda="IQD",divisa="Dinar iraquí"},
            new tipo_moneda (){id_tipo_moneda="IRR",divisa="Rial iraní"},
            new tipo_moneda (){id_tipo_moneda="ISK",divisa="Corona islandesa"},
            new tipo_moneda (){id_tipo_moneda="JMD",divisa="Dólar jamaiquino"},
            new tipo_moneda (){id_tipo_moneda="JOD",divisa="Dinar jordano"},
            new tipo_moneda (){id_tipo_moneda="JPY",divisa="Yen"},
            new tipo_moneda (){id_tipo_moneda="KES",divisa="Chelín keniano"},
            new tipo_moneda (){id_tipo_moneda="KGS",divisa="Som"},
            new tipo_moneda (){id_tipo_moneda="KHR",divisa="Riel"},
            new tipo_moneda (){id_tipo_moneda="KMF",divisa="Franco comorense"},
            new tipo_moneda (){id_tipo_moneda="KPW",divisa="Won norcoreano"},
            new tipo_moneda (){id_tipo_moneda="KRW",divisa="Won"},
            new tipo_moneda (){id_tipo_moneda="KWD",divisa="Dinar kuwaití"},
            new tipo_moneda (){id_tipo_moneda="KYD",divisa="Dólar de las Islas Caimán"},
            new tipo_moneda (){id_tipo_moneda="KZT",divisa="Tenge"},
            new tipo_moneda (){id_tipo_moneda="LAK",divisa="Kip"},
            new tipo_moneda (){id_tipo_moneda="LBP",divisa="Libra libanesa"},
            new tipo_moneda (){id_tipo_moneda="LKR",divisa="Rupia de Sri Lanka"},
            new tipo_moneda (){id_tipo_moneda="LRD",divisa="Dólar liberiano"},
            new tipo_moneda (){id_tipo_moneda="LSL",divisa="Loti"},
            new tipo_moneda (){id_tipo_moneda="LYD",divisa="Dinar libio"},
            new tipo_moneda (){id_tipo_moneda="MAD",divisa="Dírham marroquí"},
            new tipo_moneda (){id_tipo_moneda="MDL",divisa="Leu moldavo"},
            new tipo_moneda (){id_tipo_moneda="MGA",divisa="Ariary malgache"},
            new tipo_moneda (){id_tipo_moneda="MKD",divisa="Denar"},
            new tipo_moneda (){id_tipo_moneda="MMK",divisa="Kyat"},
            new tipo_moneda (){id_tipo_moneda="MNT",divisa="Tugrik"},
            new tipo_moneda (){id_tipo_moneda="MOP",divisa="Pataca"},
            new tipo_moneda (){id_tipo_moneda="MRU",divisa="Uguiya"},
            new tipo_moneda (){id_tipo_moneda="MUR",divisa="Rupia de Mauricio"},
            new tipo_moneda (){id_tipo_moneda="MVR",divisa="Rufiyaa"},
            new tipo_moneda (){id_tipo_moneda="MWK",divisa="Kwacha"},
            new tipo_moneda (){id_tipo_moneda="MXN",divisa="Peso mexicano"},
            new tipo_moneda (){id_tipo_moneda="MXV",divisa="Unidad de Inversión (UDI) mexicana"},
            new tipo_moneda (){id_tipo_moneda="MYR",divisa="Ringgit malayo"},
            new tipo_moneda (){id_tipo_moneda="MZN",divisa="Metical mozambiqueño"},
            new tipo_moneda (){id_tipo_moneda="NAD",divisa="Dólar namibio"},
            new tipo_moneda (){id_tipo_moneda="NGN",divisa="Naira"},
            new tipo_moneda (){id_tipo_moneda="NIO",divisa="Córdoba"},
            new tipo_moneda (){id_tipo_moneda="NOK",divisa="Corona noruega"},
            new tipo_moneda (){id_tipo_moneda="NPR",divisa="Rupia nepalí"},
            new tipo_moneda (){id_tipo_moneda="NZD",divisa="Dólar neozelandés"},
            new tipo_moneda (){id_tipo_moneda="OMR",divisa="Rial omaní"},
            new tipo_moneda (){id_tipo_moneda="PAB",divisa="Balboa"},
            new tipo_moneda (){id_tipo_moneda="PEN",divisa="Sol",usual=true},
            new tipo_moneda (){id_tipo_moneda="PGK",divisa="Kina"},
            new tipo_moneda (){id_tipo_moneda="PHP",divisa="Peso filipino"},
            new tipo_moneda (){id_tipo_moneda="PKR",divisa="Rupia pakistaní"},
            new tipo_moneda (){id_tipo_moneda="PLN",divisa="Złoty"},
            new tipo_moneda (){id_tipo_moneda="PYG",divisa="Guaraní"},
            new tipo_moneda (){id_tipo_moneda="QAR",divisa="Riyal qatarí"},
            new tipo_moneda (){id_tipo_moneda="RON",divisa="Leu rumano"},
            new tipo_moneda (){id_tipo_moneda="RSD",divisa="Dinar serbio"},
            new tipo_moneda (){id_tipo_moneda="RUB",divisa="Rublo ruso"},
            new tipo_moneda (){id_tipo_moneda="RWF",divisa="Franco ruandés"},
            new tipo_moneda (){id_tipo_moneda="SAR",divisa="Riyal saudí"},
            new tipo_moneda (){id_tipo_moneda="SBD",divisa="Dólar de las Islas Salomón"},
            new tipo_moneda (){id_tipo_moneda="SCR",divisa="Rupia seychelense"},
            new tipo_moneda (){id_tipo_moneda="SDG",divisa="Dinar sudanés"},
            new tipo_moneda (){id_tipo_moneda="SEK",divisa="Corona sueca"},
            new tipo_moneda (){id_tipo_moneda="SGD",divisa="Dólar de Singapur"},
            new tipo_moneda (){id_tipo_moneda="SHP",divisa="Libra de Santa Elena"},
            new tipo_moneda (){id_tipo_moneda="SLL",divisa="Leone"},
            new tipo_moneda (){id_tipo_moneda="SOS",divisa="Chelín somalí"},
            new tipo_moneda (){id_tipo_moneda="SRD",divisa="Dólar surinamés"},
            new tipo_moneda (){id_tipo_moneda="SSP",divisa="Libra sursudanesa"},
            new tipo_moneda (){id_tipo_moneda="STN",divisa="Dobra"},
            new tipo_moneda (){id_tipo_moneda="SVC",divisa="Colon Salvadoreño"},
            new tipo_moneda (){id_tipo_moneda="SYP",divisa="Libra siria"},
            new tipo_moneda (){id_tipo_moneda="SZL",divisa="Lilangeni"},
            new tipo_moneda (){id_tipo_moneda="THB",divisa="Baht"},
            new tipo_moneda (){id_tipo_moneda="TJS",divisa="Somoni tayiko"},
            new tipo_moneda (){id_tipo_moneda="TMT",divisa="Manat turcomano"},
            new tipo_moneda (){id_tipo_moneda="TND",divisa="Dinar tunecino"},
            new tipo_moneda (){id_tipo_moneda="TOP",divisa="Paʻanga"},
            new tipo_moneda (){id_tipo_moneda="TRY",divisa="Lira turca"},
            new tipo_moneda (){id_tipo_moneda="TTD",divisa="Dólar de Trinidad y Tobago"},
            new tipo_moneda (){id_tipo_moneda="TWD",divisa="Nuevo dólar taiwanés"},
            new tipo_moneda (){id_tipo_moneda="TZS",divisa="Chelín tanzano"},
            new tipo_moneda (){id_tipo_moneda="UAH",divisa="Grivna"},
            new tipo_moneda (){id_tipo_moneda="UGX",divisa="Chelín ugandés"},
            new tipo_moneda (){id_tipo_moneda="USD",divisa="Dólar estadounidense",usual=true},
            new tipo_moneda (){id_tipo_moneda="USN",divisa="Dólar estadounidense (Siguiente día)"},
            new tipo_moneda (){id_tipo_moneda="UYI",divisa="Peso en Unidades Indexadas (Uruguay)"},
            new tipo_moneda (){id_tipo_moneda="UYU",divisa="Peso uruguayo"},
            new tipo_moneda (){id_tipo_moneda="UYW",divisa="Unidad Previsional"},
            new tipo_moneda (){id_tipo_moneda="UZS",divisa="Som uzbeko"},
            new tipo_moneda (){id_tipo_moneda="VES",divisa="Bolívar soberano"},
            new tipo_moneda (){id_tipo_moneda="VND",divisa="Dong vietnamita"},
            new tipo_moneda (){id_tipo_moneda="VUV",divisa="Vatu"},
            new tipo_moneda (){id_tipo_moneda="WST",divisa="Tala"},
            new tipo_moneda (){id_tipo_moneda="XAF",divisa="Franco CFA de África Central"},
            new tipo_moneda (){id_tipo_moneda="XAG",divisa="Plata (una onza troy)"},
            new tipo_moneda (){id_tipo_moneda="XAU",divisa="Oro (una onza troy)"},
            new tipo_moneda (){id_tipo_moneda="XBA",divisa="Unidad compuesta europea (EURCO) (Unidad del mercados de bonos)"},
            new tipo_moneda (){id_tipo_moneda="XBB",divisa="Unidad Monetaria europea (E.M.U.-6) (Unidad del mercado de bonos)"},
            new tipo_moneda (){id_tipo_moneda="XBC",divisa="Unidad europea de cuenta 9 (E.U.A.-9) (Unidad del mercado de bonos)"},
            new tipo_moneda (){id_tipo_moneda="XBD",divisa="Unidad europea de cuenta 17 (E.U.A.-17) (Unidad del mercado de bonos)"},
            new tipo_moneda (){id_tipo_moneda="XCD",divisa="Dólar del Caribe Oriental"},
            new tipo_moneda (){id_tipo_moneda="XDR",divisa="Derechos especiales de giro"},
            new tipo_moneda (){id_tipo_moneda="XOF",divisa="Franco CFA de África Occidental"},
            new tipo_moneda (){id_tipo_moneda="XPD",divisa="Paladio (una onza troy)"},
            new tipo_moneda (){id_tipo_moneda="XPF",divisa="Franco CFP"},
            new tipo_moneda (){id_tipo_moneda="XPT",divisa="Platino (una onza troy)"},
            new tipo_moneda (){id_tipo_moneda="XSU",divisa="SUCRE"},
            new tipo_moneda (){id_tipo_moneda="XTS",divisa="Reservado para pruebas"},
            new tipo_moneda (){id_tipo_moneda="XUA",divisa="Unidad de cuenta BAD"},
            new tipo_moneda (){id_tipo_moneda="XXX",divisa="Sin divisa"},
            new tipo_moneda (){id_tipo_moneda="YER",divisa="Rial yemení"},
            new tipo_moneda (){id_tipo_moneda="ZAR",divisa="Rand"},
            new tipo_moneda (){id_tipo_moneda="ZMW",divisa="Kwacha zambiano"},
            new tipo_moneda (){id_tipo_moneda="ZWL",divisa="Dólar zimbabuense"},

        };
        

        
    }
}

